name: CI/CD Main

on:
  push:
    branches:
      - "main"

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Backend
      - name: Install Backend dependencies
        working-directory: backend
        run: npm install

      - name: Lint Backend
        working-directory: backend
        run: npm run lint

      - name: Test Backend
        working-directory: backend
        run: npm test

      - name: Upload Backend Test Results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/test-results/jest

      # Frontend
      - name: Install Frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Lint Frontend
        working-directory: frontend
        run: npm run lint

      - name: Test Frontend
        working-directory: frontend
        run: npm test

      - name: Upload Frontend Test Results
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: frontend/test-results/frontend

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist

      # Docker
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        working-directory: backend
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/sport-analytics-backend:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/sport-analytics-backend:latest
